# Generated by Django 4.0.3 on 2022-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Narsa', models.IntegerField(default=30)),
                ('taxe_paiment', models.FloatField(default=0)),
                ('taxe_fiscale', models.IntegerField(default=30)),
                ('taxe_communale', models.IntegerField(default=50)),
                ('paiment', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('montant_net', models.IntegerField(default=200)),
                ('montant_total', models.FloatField()),
            ],
        ),
    ]
